### ISSUE TITLE
Question: Is there a way have access to full logseq.DB while using dev mode with HMR?

### ISSUE THREAD

**Issue by mattmazzola** [haydenull/logseq-plugin-react-boilerplate#1]
From my current understanding, when running in dev mode (`vite`) queries the database will always return an empty set.

This makes dev mode unlikely to be usable for plugin testing without set up of Mock data.

https://github.com/haydenull/logseq-plugin-react-boilerplate/blob/5e62bf783b0a74e6c386d6841a2b156d2ff9eb39/src/main.tsx#L9-L11

There is a process of:

1. npm run build
2. open LogSeq plugins pane
3. reload plugin
4. activate plugin by clicking icon in toolbar

This requirement to rebuild and reload slows down development inner loop.

Is my understanding about limitations above correct?
Is there a way to access the full logseq data using development mode?

**Comment by haydenull** [comment]
‌‌‌Sorry, the current code is quite old. Today I will update a new version that supports logseq API.

**Comment by haydenull** [comment]
‌‌‌‌The code has been updated. Please note that the plugin mode does not support HMR, only the Browser mode supports it.

**Comment by mattmazzola** [comment]
> Sorry

No need to be sorry! 
That was a very quick response and solution!

I was trying to manually migrate from your other plugin [logseq-plugin-agegenda](https://github.com/haydenull/logseq-plugin-agenda) but much more confident it is done properly since you did it👍

https://github.com/haydenull/logseq-plugin-agenda/blob/1f4d58e3ce4a392d8140b5eec637a6b4e3b1030e/package.json#L11

https://github.com/haydenull/logseq-plugin-agenda/blob/1f4d58e3ce4a392d8140b5eec637a6b4e3b1030e/src/main.tsx#L51-L68

I'm thankful you created this starter template, or I probably would not have tried to create a plugin 😅
